"""Readable-label map: relabels machine column names and cell values to publication labels."""
import pandas as pd

PRETTY = {
    "variable": "Indicator",
    "n_years": "N (years)",
    "n_districts": "N (districts)",
    "n_points": "N (points)",
    "mean": "Mean",
    "sd": "SD",
    "min": "Min",
    "max": "Max",
    "median": "Median",
    "first_year": "First year",
    "last_year": "Last year",
    "forecast_tier": "Forecast tier",
    "trend": "Trend",
    "p_value": "P value",
    "sens_slope": "Sen's slope",
    "significant_at_0.05": "Significant (p<0.05)",
    "window": "Window",
    "mk_trend": "Mann-Kendall trend",
    "mk_p": "Mann-Kendall p",
    "arima_one_step_forecast_next_year": "ARIMA 1-step forecast (next yr)",
    "feature": "Feature",
    "mean_abs_shap": "Mean |SHAP|",
    # indicator/variable name values
    "tb_incidence_per100k": "TB incidence /100k",
    "tb_incidence_hiv_pos_per100k": "TB incidence, HIV+ /100k",
    "tb_new_relapse_notified": "New + relapse notified cases",
    "tb_incident_cases_total": "Incident TB cases (total)",
    "tb_incident_cases_hiv_pos": "Incident TB cases, HIV+",
    "tb_incident_cases_children_0_14": "Incident TB cases, age 0-14",
    "tb_treatment_coverage_pct": "Treatment coverage (%)",
    "tx_success_new_pct": "Tx success, new cases (%)",
    "tx_success_prev_treated_pct": "Tx success, previously treated (%)",
    "tx_success_mdr_pct": "Tx success, MDR-TB (%)",
    "tx_success_xdr_pct": "Tx success, XDR-TB (%)",
    "tx_success_hiv_pos_pct": "Tx success, HIV+ (%)",
    "mdr_rr_tb_estimated_incident": "MDR/RR-TB estimated incident cases",
    "mdr_rr_tb_confirmed": "MDR/RR-TB confirmed cases",
    "mdr_tb_started_treatment": "MDR-TB started treatment",
    "new_cases_tested_rr_mdr_pct": "New cases tested for RR/MDR (%)",
    "prev_treated_tested_rr_mdr_pct": "Prev. treated tested for RR/MDR (%)",
    "hiv_prevalence_adult_15_49_pct": "HIV prevalence, adults 15-49 (%)",
    "art_coverage_plhiv_pct": "ART coverage among PLHIV (%)",
    "tb_hiv_pos_on_art_pct": "TB-HIV+ patients on ART (%)",
    "tb_known_hiv_status_pct": "TB patients, known HIV status (%)",
    "tb_tested_hiv_positive_pct": "TB patients tested HIV+ (%)",
    "gghe_d_pct_gdp": "Govt. health expenditure (% GDP)",
    "medical_doctors_density": "Medical doctors /10,000",
    "life_expectancy_years": "Life expectancy (years)",
    "poverty_incidence": "Poverty incidence (%)",
    "poverty_intensity": "Poverty intensity",
    "literacy_rate": "Literacy rate",
    "uninsured_rate": "Uninsured rate",
    "unemployment_rate": "Unemployment rate",
    "dependency_ratio": "Dependency ratio",
    "total_population": "Total population",
    "lag_1yr": "Lag 1yr",
    "lag_2yr": "Lag 2yr",
    "lag_3yr": "Lag 3yr",
    "descriptive_only_excluded": "Descriptive only",
    "forecast_eligible": "Forecast-eligible",
    "increasing": "Increasing",
    "decreasing": "Decreasing",
    "no trend": "No trend",
}


def relabel_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.rename(columns=lambda c: PRETTY.get(c, c))
    return df.map(lambda v: PRETTY.get(v, v) if isinstance(v, str) else v)
